name: release

on:
   push:
      branches:
         - main
      paths:
         - CHANGELOG.md
   workflow_dispatch:

jobs:
   extractChangelog:
      uses: bosesuneha/action-release-workflows/.github/workflows/extract_changelog.yaml@main
      with:
         changelogPath: ./CHANGELOG.md
   checkVersion:
      needs: extractChangelog
      runs-on: ubuntu-latest
      outputs:
         exists: ${{ steps.tag-exists.outputs.exists }}
      steps:
         - name: check if tag exists
           uses: mukunku/tag-exists-action@5dfe2bf779fe5259360bb10b2041676713dcc8a3 # v1.1.0
           id: tag-exists
           with:
              tag: ${{ needs.extractChangelog.outputs.version }}
           env:
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
   createBranch:
      needs: [extractChangelog, checkVersion]
      if: needs.checkVersion.outputs.exists == 'false'
      uses: bosesuneha/action-release-workflows/.github/workflows/create_js_branch.yaml@main
      with:
         version: ${{ needs.extractChangelog.outputs.version }}
   createRelease:
      needs: [extractChangelog, checkVersion, createBranch]
      permissions:
         contents: write
      uses: bosesuneha/action-release-workflows/.github/workflows/create_release.yaml@main
      with:
         branch: releases/${{ needs.extractChangelog.outputs.version }}
         version: ${{ needs.extractChangelog.outputs.version }}
         body: ${{ needs.extractChangelog.outputs.body }}
