name: release

on:
  push:
    branches:
      - main
    paths:
      - CHANGELOG.md
  workflow_dispatch:
  workflow_call:

jobs:
  changelog:
    uses: bosesuneha/action-release-workflows/.github/workflows/extract_changelog.yaml@main
    with:
      changelogPath: ./CHANGELOG.md
  checkVersion:
    needs: changelog
    runs-on: ubuntu-latest
    outputs:
      exists: ${{ steps.tag-exists.outputs.exists }}
    steps:
      - name: check if tag exists
        uses: mukunku/tag-exists-action@5dfe2bf779fe5259360bb10b2041676713dcc8a3 # v1.1.0
        id: tag-exists
        with:
          tag: ${{ needs.changelog.outputs.version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  createRelease:
    needs: [checkVersion, changelog]
    permissions:
      contents: write
    if: needs.checkVersion.outputs.exists == 'false'
    uses: bosesuneha/action-release-workflows/.github/workflows/create_release.yaml@main
    with:
      branch: ${{ github.ref }}
      version: ${{ needs.changelog.outputs.version }}
      body: ${{ needs.changelog.outputs.body }}