name: release

on:
   push:
      branches:
         - main
      paths:
         - CHANGELOG.md
   workflow_dispatch:

jobs:
   release:
      uses: bosesuneha/action-release-workflows/.github/workflows/release.yaml@main
      with:
         changelogPath: ./CHANGELOG.md
   
